"""Make movie title unique

Revision ID: 384f9f75906d
Revises: 2d452f074614
Create Date: 2025-06-30 16:47:47.107277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384f9f75906d'
down_revision: Union[str, Sequence[str], None] = '2d452f074614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_movie_title', ['title'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_constraint('unique_movie_title', type_='unique')

    # ### end Alembic commands ###
