"""Add MovieRating rating field

Revision ID: 3b7c29986b9b
Revises: 9f2e3ebf94d2
Create Date: 2025-07-01 19:02:00.728629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7c29986b9b'
down_revision: Union[str, Sequence[str], None] = '9f2e3ebf94d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_rating', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_ratings', schema=None) as batch_op:
        batch_op.drop_column('movie_rating')

    # ### end Alembic commands ###
